name: flutter_facebook_auth_platform_interface
description: A common platform interface for the flutter_facebook_auth plugin.
version: 2.0.0-nullsafety.0
homepage: https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/flutter_facebook_auth_platform_interface

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.1.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter


