name: Bug Report
description: Create a bug report for the flutter_facebook_auth
labels: 'template: bug'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: markdown
    attributes:
      value: If you leave out sections there is a high likelihood that this issue will be closed
  - type: input
    attributes:
      label: What version are you using? (if relevant)
      description: 'Please specify the exact version. For example: flutter_facebook_auth:4.3.4'
  - type: input
    attributes:
      label: What SO are you using to local deploy your application? (if relevant)
      description: 'For example: macOS, windows 11, Ubuntu, etc'
  - type: dropdown
    id: platforms
    attributes:
      label: What platforms are you seeing the problem on?
      multiple: true
      options:
        - Android
        - iOS
        - web
        - macOS
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior, please provide a clear code snippets that always reproduces the issue or a GitHub repository. Screenshots can be provided in the issue body below.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Your dart code used to log in.
      render: dart
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell  
  - type: textarea
    attributes:
      label: flutter doctor -v
      description: Please copy and paste the output `flutter doctor -v`
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Info.plist (iOS)
      description: Add this only if the problem is happening on iOS.
      render: xml
    validations:
      required: false
  - type: textarea
    attributes:
      label: AndroidManifest.xml
      description: Add this only if the problem is happening on Android.
      render: xml
    validations:
      required: false
  - type: textarea
    attributes:
      label: MainActivity.java
      description: Add this only if the problem is happening on Android and if your android project uses java as default language.
      render: java
  - type: textarea
    attributes:
      label: MainActivity.kt
      description: Add this only if the problem is happening on Android and if your android project uses kotlin as default language.
      render: kotlin
    validations:
      required: false
  - type: textarea
    attributes:
      label: index.html
      description: Add this only if the problem is happening on Web.
      render: html
    validations:
      required: false
  - type: textarea
    attributes:
      label: Info.plist (macOS)
      description: Add this only if the problem is happening on macOS.
      render: xml
    validations:
      required: false
  - type: markdown
    attributes:
      value: Before posting the issue go through the steps you've written down to make sure the steps provided are detailed and clear.
