name: Bug report
about: Create a report to help us improve
labels: 'template: bug'

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: input
    attributes:
      label: What version of flutter_facebook_auth are you using?
      description: 'For example: 3.4.0'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: flutter doctor -v
      description: the result of the command flutter doctor -v
    validations:
      required: true

  - type: textarea
    attributes:
      label: flutter doctor -v
      description: the result of the command flutter doctor -v
    validations:
      required: true


  - type: textarea
    attributes:
      label: pubspec.yaml
      description: what dependencies are you using?
    validations:
      required: false

  - type: textarea
    attributes:
      label: AndroidManifest.xml (REQUIRED FOR ISSUES ON ANDROID)
      description: Add the code of your AndroidManifest.xml  file
    validations:
      required: false

  - type: textarea
    attributes:
      label: /app/res/values/strings.xml (REQUIRED FOR ISSUES ON ANDROID)
      description: Add the code of your strings.xml file
    validations:
      required: false

  - type: textarea
    attributes:
      label: How to reproduce
      description: Please add your code or a repository to reproduce the issue
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or videos to help explain your problem.
    validations:
      required: false


