name: flutter_facebook_auth
description: The easiest way to add facebook login to your flutter app, get user information, profile picture and more.
version: 1.0.3
homepage: https://github.com/darwin-morocho/flutter-facebook-auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth_platform_interface: ^1.0.0
  flutter_facebook_auth_web: ^1.0.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: app.meedu.flutter_facebook_auth
        pluginClass: FlutterFacebookAuthPlugin
      ios:
        pluginClass: FlutterFacebookAuthPlugin
      web:
        default_package: flutter_facebook_auth_web
        

